@startuml

title Usecase for Information system

left to right direction


actor User
actor EFreshAir
actor HealthSpecialist
actor SkulptureSpecialist

rectangle Software {

    usecase (Авторизувати користувача)
    usecase (Перегляд інформації про якість повітря)
    usecase (Звернення за консультацією щодо скульптурування)
    usecase (Звернення за консультацією щодо фізичного здоров'я)


    User -- (Авторизувати користувача)
    User -- (Перегляд інформації про якість повітря)
    User -- (Звернення за консультацією щодо скульптурування)
    User -- (Звернення за консультацією щодо фізичного здоров'я)
    SkulptureSpecialist -- (Звернення за консультацією щодо скульптурування)
    EFreshAir -- (Перегляд інформації про якість повітря)
    HealthSpecialist -- (Звернення за консультацією щодо фізичного здоров'я)

    SkulptureSpecialist --|> User
    HealthSpecialist --|> User 

   (Перегляд інформації про якість повітря) .> (Авторизувати користувача) : include
   (Звернення за консультацією щодо скульптурування) .> (Авторизувати користувача) : include
   (Звернення за консультацією щодо фізичного здоров'я) .> (Авторизувати користувача) : include

}

@enduml
