@startuml
title Activity Diagram 

start
:Користувач надсилає запит на консультацію щодо фізичного здоров'я;
if (Успішно?) then (Так)
  :Спеціаліст з фізичного здоров'я відповідає на запит;
  :Назначає час консультації;
  if (Успішно?) then (Так)
    :Користувач отримує відповідь;
  else (Ні)
    :Повідомлення про помилку;
  endif
else (Ні)
  :Очікування відповіді;
endif
stop

@enduml
