name: DataSchemaCodeConvention
on:
  push:
    branches: main 
jobs:
  sql_linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect mysql