name: ProgramCode
on: 
  push:
    branches: main
jobs:
  ProgramCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: ./*.java
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}