name: Test Cases

on:
  push:
    branches: Lab11

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile & Execute
        run: |
          cd $GITHUB_WORKSPACE/
          javac TestCases.java
          java TestCases